### ISSUE TITLE
Add key prefix

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-S3#3]
Add optional boolean key_prefix (default false) which will be prepended to the file name:

false: "S3:my_bucket/file.jpg"
true: "S3:my_bucket/some/path/file.jpg"

**Comment by macieys** [comment]
Hey,
Thanks for this integration. Very helpful.
Would you be able to add prefixes?

**Comment by robmarkcole** [comment]
@macieys any suggestions on if it should be:
- a string, and you enter the key to use?
- a boolean, as in the example I previously gave

**Comment by macieys** [comment]
@robmarkcole, I would follow Ansible s3 module pattern if possible:
```
s3:
    bucket: mybucket
    object: /my/desired/key.txt
    src: /usr/local/myfile.txt
```
It's very clean and simple.
https://docs.ansible.com/ansible/2.3/s3_module.html
