### ISSUE TITLE
Region in configuration file is ignored when I make a Sign URL Service request.

### ISSUE THREAD

**Issue by kmcgarra** [robmarkcole/HASS-S3#42]
Home Assistant OS: 12.4
Home Assistant Core: 2024.6.4
HASS-S3: 1.12 installed with HACS

The region in configuration file is ignored when I make a Sign URL Service request.

I have the following in my configuration.yaml:
```
s3:
  aws_access_key_id: <key>
  aws_secret_access_key: <secret>
  region_name: us-east-2
```

I am using the Sign URL Service request in a script:
```
get_snapshot_url:
  alias: Get snapshot URL
  sequence:
    - service: s3.signurl
      data:
        bucket: <bucket>
        key: snapshots/backyard/snapshot.jpg
        duration: 3600
```

I have confirmed the image exists on my S3 bucket.

The URL I get back gives me the following error:
`InvalidRequestThe authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`

I added a log statement to line 239 of custom_components/s3/__init__.py to log the region being used:
`_LOGGER.error("Region %s", entry.data[CONF_REGION])`

"Region us-east-1" is printed in the log.
<img width="532" alt="Screen Shot 2024-09-09 at 9 37 58 AM" src="https://github.com/user-attachments/assets/4fc23488-806f-4349-8603-82a146f59bcd">

Everything works if I hard code the region as below.
<img width="509" alt="Screen Shot 2024-09-09 at 9 33 01 AM" src="https://github.com/user-attachments/assets/d53baf46-c247-4c11-b65f-308774cca734">

The Put Service was working as expected.
